### ISSUE TITLE
Void pointers cannot be assigned

### ISSUE THREAD

**Issue by Aryan807** [denesfilotas/vscode-blitz3d#12]
In Blitz3D, you can specify "*" as type declaration for declaring functions of any userlib dll, e.g:

```
api_RtlCopyMemory(Destination,Source*,Length):"RtlMoveMemory"
api_RtlMoveMemory(Destination*,Source,Length):"RtlMoveMemory"
```

This `*` declaration means void pointer `void *`  in C and can be assigned ANY value or object. However, the extension doesn't seem to allow this assignment and if I try to pass integer("%") to any argument of userlib function which uses void pointers, it simply gives error that expression of type "%" cannot be implicitly converted to type "*".

**Comment by denesfilotas** [comment]
Hey, sorry for the delay. Nice work! I will release a new version in about a week
