### ISSUE TITLE
Userlibs with decorated names don't work

### ISSUE THREAD

**Issue by Aryan807** [denesfilotas/vscode-blitz3d#6]
Userlibs with decorated names seems to not work.

Removing the lines 169-70 of `/src/context.ts` seems to fix the issue, it seems the extension uses the decorated names instead of the names that it should use for userlibs.

**Comment by denesfilotas** [comment]
Thanks! Could you create a PR with the fix and for the typerror issue too?

Here also change name and indent to const on lines 118-119 of the same file, if possible.
