### ISSUE TITLE
Failure to assign nested types

### ISSUE THREAD

**Issue by Aryan807** [denesfilotas/vscode-blitz3d#8]
This error occurs in line 18073 of [https://github.com/ByteNybbler/MNIKEditor/blob/master/editor.bb](https://github.com/ByteNybbler/MNIKEditor/blob/master/editor.bb#L18073)

It seems the parser confuses the types of variables in these types of assignments. The code compiles and runs fine though (note that if you'll compile it will give "Directory Not Found Error" on startup which is valid as it won't find the assets to run).

**Comment by denesfilotas** [comment]
Thanks! Expression parsing relied too much on the initial type tag, however the check was also impelemented in parseVar correctly.

**Comment by Aryan807** [comment]
Umm... no, it now starts giving duplicate type error in many types [https://github.com/ByteNybbler/MNIKEditor/blob/master/editor.bb#L652](https://github.com/ByteNybbler/MNIKEditor/blob/master/editor.bb#L652)

**Comment by denesfilotas** [comment]
I think that is caused by a different commit of mine, I'm working on it. Also the error locations are not correct in userlib files, once I clear these two issues I release the next version.
