### ISSUE TITLE
Analyzer not associated with bbfile

### ISSUE THREAD

**Issue by EasyT-T** [denesfilotas/vscode-blitz3d#9]
Like you have A.bb B.bb and Main.bb
Main.bb include A.bb and B.bb
If you defined a field in A.bb
You used this field in B.bb
It will send a 'Unknown field' error

Like this:
![image](https://github.com/denesfilotas/vscode-blitz3d/assets/116633144/9b0194c7-481e-44eb-b8e4-7a5fb5bda48b)

**Comment by denesfilotas** [comment]
Hi,

Could you provide a bit more details? It seems to be working for me

Did you set the bbfile correctly in the launch configuration? Did you use absolute or relative path?
Do you have multiple folders open (workspace)?
Could you maybe share some code? I created the A.bb, B.bb and Main.bb as you said but no errors for me.

Also just released an update with some older commits that should be unrelated but you might try with the new version.

**Comment by EasyT-T** [comment]
Alright, in new version, it works well.
